port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

proxies:
  - name: ${NAME}
    type: trojan
    server: ${SERVER}
    port: 443
    password: ${PASSWORD}
    sni: ${SNI}
    udp: false
  - name: ${NAME}(WS)
    type: trojan
    network: ws
    server: ${WS_SERVER}
    port: 443
    password: ${PASSWORD}
    sni: ${SNI}
    udp: false
    ws-opts:
      path: /api/ws
      headers:
        Host: ${SNI}

proxy-groups:
  - name: Automatic
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ${NAME}
      - ${NAME}(WS)
  - name: Fallback
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - ${NAME}
      - ${NAME}(WS)
  - name: Manual
    type: select
    proxies:
      - Automatic
      - Fallback
      - ${NAME}
      - ${NAME}(WS)
  - name: Final
    type: select
    proxies:
      - Manual
      - DIRECT

rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Final



