run-type: server
local-addr: 127.0.0.1
local-port: 1080
remote-addr: 127.0.0.1
remote-port: 80
password:
  - ${PASSWORD}
ssl:
  cert: ${CERTIFICATE_FULLCHAIN}
  key: ${CERTIFICATE_KEY}
  sni: ${SNI}
  fallback-addr: 127.0.0.1
  fallback-port: 444
websocket:
  enabled: true
  path: /api/ws
  host: ${SNI}
tcp:
  no-delay: true
  keep-alive: true
  prefer-ipv4: false
